spring:
  datasource:
    url: jdbc:mysql://localhost:3306/entity_redis
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        format_sql: true
#        generate_statistics: true
#        dialect: org.hibernate.dialect.MySQL8Dialect
        cache:
          use_query_cache: true
          use_second_level_cache: true
          region:
            factory_class: org.redisson.hibernate.RedissonRegionFactory
#          redisson:
#            entity:
#              expiration:
#                time_to_live: 60000
#                max_idle_time: 30000
#            collection:
#              expiration:
#                time_to_live: 60000
#                max_idle_time: 30000
          connection:
            provider_disables_autocommit: true
          redisson-config: classpath:redisson.yaml
      javax:
        persistence:
          sharedCache:
            mode: ALL

logging:
  level:
    root: INFO
    sql: debug
#    org.hibernate.cache: TRACE